### ISSUE TITLE
Error on eval server

### ISSUE THREAD

**Issue by mazatov** [SoccerNet/sn-calibration#15]
Got this error on eval.ai server. Looks like the change in the code regarding the empty json hasn't been udpated on eval.ai. 
```
Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 491, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmp158t3rwm/compute/challenge_data/challenge_1537/main.py", line 62, in evaluate
    results_05 = evaluate_field(test_annotation_file, user_submission_file, threshold=5)
  File "/usr/local/lib/python3.7/site-packages/SoccerNet/Evaluation/FieldCalibration.py", line 49, in evaluate
    threshold)
  File "/usr/local/lib/python3.7/site-packages/SoccerNet/Evaluation/utils_calibration.py", line 261, in evaluate_detection_prediction
    groundtruth_classes = set(groundtruth_lines.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by fmagera** [comment]
Yes the change are not yet made on the server for this issue and the circle central class issue. We will keep you updated when it is done !

**Comment by mazatov** [comment]
Awesome thanks! Can't wait to submit the challenge dataset to see the results! 

For the test, I just removed the empty file and submitted it like that eventually, but don't want to waste my challenge submissions like that :)
